name: Update Trusted Tools

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
  schedule:
  # Runs weekly, every Saturday at 02:00 UTC (alligned with off-peak hours)
    - cron: "0 2 * * SAT"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10, 3.11] # test to see what Python versons are compatible
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Clone usegalaxy-eu-tools repository
        uses: actions/checkout@v4
        with:
          repository: usegalaxy-eu/usegalaxy-eu-tools
          path: usegalaxy-eu-tools
          ref: master
      - name: Update tools_iuc.yaml from tools_iuc_eu.yaml
        run: |
          python3 process_yaml.py --merge_yaml --base_file tools_iuc.yaml --tools_yaml ${GITHUB_WORKSPACE}/usegalaxy-eu-tools/tools_iuc.yaml --out_file tools_iuc.yaml
      - name: Deleting usegalaxy-eu-tools repository
        run: rm -r usegalaxy-eu-tools
      - name: Perform linting
        run: |
            # Update the trusted tools.
            make fix -j $(nproc)
            make lint -j $(nproc)
            make update_trusted -j $(nproc)
      - name: Show differences
        run: "git diff --stat"
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update Galaxy tools
          title: "Automatic updating of the tools in tools-iuc.yaml"
          body: |
            This PR is automatically generated based on changes in the [usegalaxy.* tools](https://github.com/usegalaxy-eu/usegalaxy-eu-tools) tools
            and updates to our own tools and new tools added.
            Please verify if these changes are valid.
          labels: |
            automatic PR
          branch: tools-update
          base: master
      - name: Check output
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
